### ISSUE TITLE
How to hire a junior developer

### ISSUE THREAD

**Issue by niktayv** [csrail/hangman-sinatra#1]
Hi Corny! 

Sorry, could not find other way to message you. Look at what I found to follow up our conversation yesterday night: https://medium.com/@_ericelliott/hiring-junior-developers-isn-t-about-what-they-know-now-it-s-about-their-ability-and-eagerness-to-13384e57263#.u0d2se2td 

Regards,
Yuri

**Comment by csrail** [comment]
Haha @yurivyatkin 
Thanks for this. I only just noticed :)

Feel free to email me in the future!
You retweet the most hilarious things on twitter.
This one on asset pipeline was hilarious:https://twitter.com/thomasfuchs/status/751389598501265408

**Comment by niktayv** [comment]
@csrail Please check my messages in meetup.com
